### ISSUE TITLE
Issue classification and labelling

### ISSUE THREAD

**Issue by Glavin001** [Glavin001/IssueBot#2]
See http://scikit-learn.org/stable/auto_examples/document_classification_20newsgroups.html

Classify and automatically label issues.

**Comment by MatKallada** [comment]
Hmm - interesting idea; I think you should stick to something simple.

Here's an idea: for a new issue: vectorize it (using whatever, TF-IDF works), and calculate the similarity between all other issues using a distance metric. You can infer the duplicates using the obtained distances.

Remember the <a href="http://en.wikipedia.org/wiki/Curse_of_dimensionality">curse of dimensionality</a>: you might have to spend some time finding an appropriate distance metric. Euclidean distance is likely to fail here.

**Comment by Glavin001** [comment]
Thanks for your feedback, @kallada. 

For issue #1 I was using TF-IDF (see [detect_duplicates.py](https://github.com/Glavin001/IssueBot/blob/master/detect_duplicates.py) ) and that worked to detect _very_ similar Issues and recognize them as duplicates, however there is much desire for improvement. I am still new to scikit-learn. Are you suggesting that I try each of the [distance metrics provided by scikit-learn](http://scikit-learn.org/stable/modules/generated/sklearn.neighbors.DistanceMetric.html) and see which obtains the best results?

I'd love to have an expert contributor, if you are interested.

**Comment by MatKallada** [comment]
> Are you suggesting that I try each of the distance metrics provided by scikit-learn and see which obtains the best results?

Yeah. In a lot of cases the distance metric can be treated as a <a href="http://en.wikipedia.org/wiki/Hyperparameter_optimization">tunable hyperparameter</a>. There's even an entire area of ML research called <a href="http://en.wikipedia.org/wiki/Similarity_learning#Metric_learning">metric learning</a> which tries to learn good distance functions automatically - but it's pretty new. 

> I'd love to have an expert contributor, if you are interested.

Thanks for the offer - super busy ATM with some other projects; ping me whenever you need advice!

**Comment by Glavin001** [comment]
Looking into http://stackoverflow.com/a/10527953/2578205

**Update**: Use http://stackoverflow.com/a/19172087/2578205 with `lb = preprocessing.MultiLabelBinarizer()` as recommended in the comment, for most up-to-date code.

**Comment by Glavin001** [comment]
Look into using 10-fold cross-validation for model validation: http://scikit-learn.org/stable/modules/cross_validation.html

**Comment by Glavin001** [comment]
Classification when 80% of my training set is of one class.: https://www.reddit.com/r/MachineLearning/comments/12evgi/classification_when_80_of_my_training_set_is_of/

8 Tactics to Combat Imbalanced Classes in Your Machine Learning Dataset: http://machinelearningmastery.com/tactics-to-combat-imbalanced-classes-in-your-machine-learning-dataset/

**Comment by Glavin001** [comment]
Document Classification with scikit-learn: http://zacstewart.com/2015/04/28/document-classification-with-scikit-learn.html

**Comment by Glavin001** [comment]
Receiving error: `Error: ValueError: You appear to be using a legacy multi-label data representation. Sequence of sequences are no longer supported; use a binary array or sparse matrix instead.`

Found possible solution: http://stackoverflow.com/a/34276057/2578205
And also look at http://scikit-learn.org/stable/modules/multiclass.html#multilabel-classification-format

**Comment by Glavin001** [comment]
Calculating confidence for labelling:
- Classification algorithms that return confidence?: http://stats.stackexchange.com/questions/113458/classification-algorithms-that-return-confidence
- The Meaning of Confidence: http://hunch.net/?p=317
- Probability calibration of classifiers: http://scikit-learn.org/stable/auto_examples/calibration/plot_calibration.html
- How to get a classifier's confidence score for a prediction in sklearn?: http://stackoverflow.com/a/31129888/2578205
- test_label_binarizer_iris() : https://searchcode.com/codesearch/view/94225751/
- Scores and probabilities: http://scikit-learn.org/stable/modules/svm.html#scores-probabilities
- sklearn.svm.SVC.score() : http://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html#sklearn.svm.SVC.score
- sklearn.svm.LinearSVC.decision_function() : http://scikit-learn.org/stable/modules/generated/sklearn.svm.LinearSVC.html#sklearn.svm.LinearSVC.decision_function

**Comment by Glavin001** [comment]
Cannot compute a Confusion Matrix until multilabel is supported: https://github.com/scikit-learn/scikit-learn/issues/3452

Error I receive:

```
Traceback (most recent call last):
  File "scripts/multi-label_classification.py", line 27, in <module>
    results = classifier.train_issues(user, repo, issues, ignore_labels)
  File "scripts/../src/classifier/classifier.py", line 266, in train_issues
    confusion_matrix = str(metrics.confusion_matrix(Y, pred_y))
  File "/usr/local/lib/python2.7/site-packages/sklearn/metrics/classification.py", line 235, in confusion_matrix
    raise ValueError("%s is not supported" % y_type)
ValueError: multilabel-indicator is not supported
```
