### ISSUE TITLE
GitHub Integration

### ISSUE THREAD

**Issue by Glavin001** [Glavin001/IssueBot#3]
Facebook's mention-bot actually has a fairly simple setup process: https://github.com/facebook/mention-bot

---

Tasks:
- [x] Retrieve list of Issues for a given repository
  - https://developer.github.com/v3/issues/#list-issues-for-a-repository
- [x] Retrieve contents for single issue
  - https://developer.github.com/v3/issues/#get-a-single-issue

**Comment by Glavin001** [comment]
GitHub does not provide issue-only permissions: https://help.github.com/articles/issues-only-access-permissions/

**Comment by Glavin001** [comment]
Adding a label to an issue: https://developer.github.com/v3/issues/labels/#add-labels-to-an-issue

**Comment by Glavin001** [comment]
Detect when IssueBot has been added as a collaborator to a repository: https://developer.github.com/v3/activity/events/types/#memberevent

Then setup webhooks for `issues` event:
- https://developer.github.com/v3/repos/hooks/#create-a-hook
- https://developer.github.com/v3/activity/events/types/#issuesevent

**Comment by issue-manager** [comment]
I will be the GitHub user that contributes to repositories!

**Comment by Glavin001** [comment]
Use https://ngrok.com/ for providing URL for GitHub webhook setup.

**Comment by Glavin001** [comment]
![image](https://cloud.githubusercontent.com/assets/1885333/15978205/0a12775e-2f33-11e6-8efc-a48a157f3dd7.png)

**Comment by Glavin001** [comment]
Closing in favour of more specifically tasked Issues regarding GitHub integration.
